const data = [
  {
    Deadline: "2022-03-31",
    Description: "react ",
    Duration: "9 hours",
    Email: "vijaya@gmail.com",
    FullName: "sgsg",
    PhoneNo: "298698124",
    Salary: "10000000",
    jobName: "kingsup",
    location: "america",
    title: "frontend developer",
    type: "Part Time",
  },
  {
    Deadline: "2022-03-31",
    Description: "react ",
    Duration: "9 hours",
    Email: "vijaya@gmail.com",
    FullName: "sgsg",
    PhoneNo: "298698124",
    Salary: "10000000",
    jobName: "kingsup",
    location: "america",
    title: "frontend developer",
    type: "Part Time",
  },
  {
    Deadline: "2022-03-31",
    Description: "react ",
    Duration: "9 hours",
    Email: "vijaya@gmail.com",
    FullName: "sgsg",
    PhoneNo: "298698124",
    Salary: "10000000",
    jobName: "kingsup",
    location: "america",
    title: "frontend developer",
    type: "Part Time",
  },
  {
    Deadline: "2022-03-31",
    Description: "react ",
    Duration: "9 hours",
    Email: "vijaya@gmail.com",
    FullName: "sgsg",
    PhoneNo: "298698124",
    Salary: "10000000",
    jobName: "kingsup",
    location: "america",
    title: "frontend developer",
    type: "Part Time",
  },
  {
    Deadline: "2022-03-31",
    Description: "react ",
    Duration: "9 hours",
    Email: "vijaya@gmail.com",
    FullName: "sgsg",
    PhoneNo: "298698124",
    Salary: "10000000",
    jobName: "kingsup",
    location: "america",
    title: "frontend developer",
    type: "Part Time",
    
  },
  {
    Deadline: "2022-03-31",
    Description: "react ",
    Duration: "9 hours",
    Email: "vijaya@gmail.com",
    FullName: "sgsg",
    PhoneNo: "298698124",
    Salary: "10000000",
    jobName: "kingsup",
    location: "america",
    title: "frontend developer",
    type: "Part Time",
  },
];

export default data;
