const FAQData = [
    {
        que: "What is Community Service and Volunteering?",
        ans: "Community service is unpaid work performed by a person or group of people for the benefit and betterment of their community without any form of compensation. Community service can be distinct from volunteering, since it is not always performed on a voluntary basis and may be compulsory."
    },
    {
        que: "What is SAHYOG?",
        ans: "SAHYOG provides its users various volunteering oppurtunities. Users can choose to perform them at their spare time. Users can also post various volunteering oppurtunities generated by them for other users."
    },
    {
        que: "How does Community service impact an Invidual?",
        ans: "Community Service is a great way to help someone, even in a small way. Also helping and interacting with other people always puts a smile on your face."
    },
    {
        que: "Can you donate money through SAHYOG?",
        ans: "SAHYOG's majorly promotes volunteering personally for various oppurtunities and not on money donations. However, one can donate money also."
    },
    {
        que: "Who is eligible for volunteering?",
        ans: "Any citizen who is willing to come forward to contribute towards the well being of individuals to bring upon transformation and thus contribute towards growth of the society as whole is invited."
    },
];

export default FAQData;